### ISSUE TITLE
not work with nested JSON file

### ISSUE THREAD

**Issue by Lowell130** [jhsu98/json-splitter#1]
hello, seem not work with nested JSON file, like this:

`{
    "Items": {
        "Item": [
            {
                "key1": "value1",
                "key2": "value2",
                "key3": {
                    "key4": [
                        "value4"
                    ]
                }
            }
        ]
    }
}`

**Comment by jhsu98** [comment]
Yes, the script requires the JSON file to be an array of objects. It could easily be forked and modified to accommodate your needs. Basically you'd want to add a couple lines after loading the JSON file to navigate down into `Items` then into `Item` which is where your array of objects can be found.

**Comment by Lowell130** [comment]
> Yes, the script requires the JSON file to be an array of objects. It could easily be forked and modified to accommodate your needs. Basically you'd want to add a couple lines after loading the JSON file to navigate down into `Items` then into `Item` which is where your array of objects can be found.

can you help me do that, please?
